version: '3.1'
#Default user: root
services:

  djangodb:
    image: mysql:5.7
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: django
    ports:
      - 33061:3306

  adminer:
    image: adminer
    restart: always
    ports:
      - 8080:8080