# Generated by Django 4.0.3 on 2022-04-12 08:29

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Departments',
            fields=[
                ('department_id', models.AutoField(primary_key=True, serialize=False)),
                ('department_name', models.CharField(max_length=500)),
            ],
        ),
        migrations.CreateModel(
            name='Employees',
            fields=[
                ('employee_id', models.AutoField(primary_key=True, serialize=False)),
                ('employee_name', models.CharField(max_length=500)),
                ('department', models.CharField(max_length=500)),
                ('date_of_joining', models.DateField(auto_now_add=True)),
                ('photo_filename', models.CharField(blank=True, max_length=500)),
            ],
        ),
    ]
